### PR TITLE
fix: 蜂窝和网格图层聚合属性问题

### LINKED ISSUE #38: 🐛 蜂窝和网格图层聚合属性问题
### 🐛 Bug description [Please make everyone to understand it]

1. 蜂窝和网格图层 聚合字段和聚合方法不是必选的

image

2. 当选择聚合方法其中任一一种的时候，填充字段多一个对应的选项，如选择聚合方法为 sum，填充字段下拉列表有 count 和 sum

image

### PR DESCRIPTION
**Pull request by simplexiao**
fixed #38

image

### CODE REVIEW

File: packages/li-p2/src/LayerAttribute/common-schema/grid-hexbin-color-collapse.ts [hunk 1]
```diff
@@ -32,6 +32,22 @@ export default (options: AttributeSchemaOptions) => {
...
+                },
+              },
+              {
+                dependencies: ['aggregateMethod'],
+                fulfill: {
+                  run:
+                    "$form.setFieldState('fillColorField',state=>{ state.value = $form.getFieldState( 'aggregateMethod' ,state => { return [state.value,'count']} ).includes(state.value)?state.value:undefined })",
+                },
+              },
+            ],
```
Comment (lvisei) [inline packages/li-p2/src/LayerAttribute/common-schema/grid-hexbin-color-collapse.ts:50]: image

Comment (lvisei) [reply packages/li-p2/src/LayerAttribute/common-schema/grid-hexbin-color-collapse.ts:50]: 还有一个问题 packages/li-p2/src/LayerAttribute/common-schema/grid-hexbin-color-collapse.ts 是公用给 HexbinLayerStyle 组件跑的，这些组件没有依赖 aggregateMethod 字段吧，会报错吗，还是写到 聚会方法那边？

File: packages/li-core-assets/src/layers/GridLayer/register-form/coordinate-schema.ts [hunk 2]
```diff
@@ -110,11 +109,10 @@ export default (fieldList: FieldSelectOptionType[]) => {
             aggregateMethod: {
               type: 'string',
               title: '聚合方法',
-              required: true,
-              default: 'sum',
```
Comment (lvisei) [inline packages/li-core-assets/src/layers/GridLayer/register-form/coordinate-schema.ts:114]: 这种情况 聚合字段是必须的，看能解不
image

File: packages/li-core-assets/src/layers/GridLayer/register-form/coordinate-schema.ts [hunk 3]
```diff
@@ -123,6 +130,22 @@ export default (fieldList: FieldSelectOptionType[]) => {
                 { label: 'min', value: 'min' },
                 { label: 'mean', value: 'mean' },
               ],
+              'x-reactions': [
+                {
+                  dependencies: ['aggregateMethod'],
+                  fulfill: {
+                    run:
+                      "$form.setFieldState('fillColorField',state=>{ state.dataSource = $form.getFieldState( 'aggregateMethod' ,state => { return state.value?[{value:'count',label:'count'},{label:state.value,value:state.value}]:[{value:'count',label:'count'}] } )})",
```
Comment (lvisei) [inline packages/li-core-assets/src/layers/GridLayer/register-form/coordinate-schema.ts:138]: `$form.setFieldState("fillColorField", (state) => {
  state.dataSource = $form.getFieldState("aggregateMethod", (state) => {
    return state.value
      ? [
          { value: "count", label: "count" },
          { label: state.value, value: state.value },
        ]
      : [{ value: "count", label: "count" }];
  });
});

$form.setFieldState("fillColorField", (state) => {
  state.value = $form
    .getFieldState("aggregateMethod", (state) => {
      return [state.value, "count"];
    })
    .includes(state.value)
    ? state.value
    : undefined;
});`
